### PR TITLE
Excel file format support (XLSX)

### PR DESCRIPTION
**Pull request by nbelyh**
Support for XLSX format for translations (#26)

The library used to parse XLSX files: [ExcelJS](https://github.com/exceljs/exceljs)

This PR also updates the tools to the version that makes it possible to compile ("vscode" npm package was retired and current "master" was not building)

Abstracted away working with file into "ICsvData" interface, so both CSV and XLSX can be processed with the same code with no changes.

The functional changes (XLSX support) are in this the commit "add xlsx support".

Minimum vscode version updated to 1.40 (node 12.0), to support ExcelJS. 
1.40 is still something like 4 years old, should not be too much.
Node 12 is also not supported anymore, btw, so maybe it's okay to update to even newer one.

### CODE REVIEW

**Comment by estruyf** [comment]
Thanks, @nbelyh, for these changes. It will help others. I just reviewed the code and saw you removed some functionality for comments and timestamps. If you can let me know why you did this, that would be great. As I believe this is still a valuable feature.

**Comment by nbelyh** [comment]
@estruyf thank you! I think this "review" functionality is completely covered (superseded) by the xlsx support actually.. 
I've added that [before](https://github.com/estruyf/vscode-spfx-localization/pull/16) as a solution to track the changes, but (at least for us) it worked quite poorly.
Doubt anyone (except myself) actually discovered or used this piece, to be honest.

The point was to get track of the new and updated lines.
Now it's much easier: you just set some format for the Excel sheets you have already translated/reviewed. The new lines are added with default style, so they are clearly distinguishable. Also the comments may be extra columns that are ignored by the tool.
Meaning, the support for the xlsx just streamlines the whole thing. Do you think there will actually be harm in removing this? If yes then I can revert that piece back, it's removed as a single commit. I would prefer to have it simple though, i.e. to accept that some approach was no good and just replace it wit ha better one? 😄

**Comment by nbelyh** [comment]
After giving it a second thought, restored this piece 😅 Compatibility is the king, never drop user work.
If nobody was using it, nobody will use it in the future as well, but let it be 😄

**Comment by nbelyh** [comment]
One more notice - replaced tslint with eslint (as the tslint support is dropped)

**Comment by estruyf** [comment]
> One more notice - replaced tslint with eslint (as the tslint support is dropped)

I saw that. Thanks for that update.

**Comment by estruyf** [comment]
Comments were also created as a field to mention more about where the localization key is used. In the previous company, this was used to tell the translation company more about the context of how it is used. We used a `notes` column for this, but with your change back then, something similar could be achieved.

Agree that Excel has other features built in, but as we also support CSV, it is good to keep it in as is and let the user decide how and what they want to use. Thanks for adding it in again.

**Comment by nbelyh** [comment]
I tried to keep most of the naming with "CSV", like "getCsvFilePath", although it actually may return excel file path and may be confusing. In the future, may be optimized, but for now, it could be easier to review (fewer changes). Also "CsvDataArray" is for real CSV, whereas "CsvDataExcel" is excel processor.

**Comment by estruyf** [comment]
It makes sense to change it later to `getFilePath` indeed. Will start testing out the extension updates.

**Comment by nbelyh** [comment]
Thank you! 🍻  I used the [Excel Viewer](https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer) extension for the vscode to see the content of the excel file immediately.

To switch to excel for existing project, I changed the path (file extension) in the settings, and then used the "SPFx export locale labels" command. These steps should create a replica of the .csv file, but as .xlsx.

As a possible next steps, for the company I worked with previously for example, it could be good to allow that translation file to be stored in sharepoint. Or just have some SharePoint list directly as a storage (i.e. sort of third option - CSV, Excel, SharePoint list).

**Comment by estruyf** [comment]
Tested the Excel export and import. Although it seems to work nicely, there is an issue when opening the Excel file. The first time it was created, all worked fine. Once I change and export again, the file is broken and needs to be repaired.

It seems that the extension/dependency can still read it.

image

**Comment by estruyf** [comment]
The issue occurs when I format the data as a table and perform an export.

**Comment by nbelyh** [comment]
Could you pls be more specific in steps - do I understand this correctly?
- export for the first time (fine)
- open in Excel and format as a table (fine)
- export again
- open in Excel again (the above dialog)?

**Comment by estruyf** [comment]
That is correct @nbelyh

**Comment by nbelyh** [comment]
Checking it now will come back as soon as I discover the reason/fix. Thank you for checking 👍 Sorry for not checking this scenario myself 😞

**Comment by estruyf** [comment]
@nbelyh no worries, thank you already for the fix and this enhancement!

**Comment by nbelyh** [comment]
It's something to do with AutoFilter row enabled in the ExcelJS (the auto-filter seems to be not updated properly)
Seems to be related to this: https://github.com/exceljs/exceljs/issues/400, still checking
Formatting as a table by itself seems to be no problem, it happens when auto-filter is enabled as a checkbox.

**Comment by nbelyh** [comment]
Should be fixed now. Please remove the "broken" Excel file (start over), it will not auto-heal. The problem appears to be in the library used, i.e. ExcelJS. Fixed the library 😄 but not sure how good it is maintained now, will create a PR anyway for the mentioned issue. For now just did a fork of it: https://github.com/nbelyh/exceljs

The fix (the idea is that if in the source file the value was "undefined" it should stay "undefined"). This is the only difference to the original one: https://github.com/nbelyh/exceljs/commit/2f1cd6e54bb84bd78aca6834ab5469c3c3e383f2

@estruyf Would really appreciate if find some time to re-check.
tested today with three projects, table/filter seems to be fine.

**Comment by estruyf** [comment]
Haven't had the time yet to try it out. Will try to do it during the Christmas holidays. If I would forget, just ping me.

**Comment by nbelyh** [comment]
Linked issue/PR related to ExcelJS library bug: https://github.com/exceljs/exceljs/issues/2184

**Comment by nbelyh** [comment]
@estruyf ping - regarding XLSX support for the SPFx localization extension (the Excel file issue should be fixed)

**Comment by nbelyh** [comment]
@estruyf ping - regarding XLSX support for the SPFx localization extension (the Excel file issue fixed). Could you please review when you have time.

**Comment by estruyf** [comment]
@nbelyh looks to work a lot better! This just got merged and will push out the `1.9.0` release.

**Pull request merged**
